services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: always
    privileged: true
    group_add:
      - dialout
    ports:
      - "8080:8080"
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=America/Toronto
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - mosquitto
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: iot_hub
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  iot-hub-api:
    build: .
    container_name: iot-hub-api
    restart: always
    ports:
      - "8090:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/iot_hub
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT}
      AIRTHINGS_CLIENT_ID: ${AIRTHINGS_CLIENT_ID}
      AIRTHINGS_CLIENT_SECRET: ${AIRTHINGS_CLIENT_SECRET}
      AIRTHINGS_ACCOUNT_ID: ${AIRTHINGS_ACCOUNT_ID}
      SPRING_PROFILES_ACTIVE: prod
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_TO: ${MAIL_TO}
      SINOPE_BROKER_URL: tcp://mosquitto:1883
    depends_on:
      - postgres
      - mosquitto
volumes:
  postgres_data: