spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
  mail:
    host: smtp.hostinger.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
notification:
  email-to: ${MAIL_TO}
server:
  port: 8080
airthings:
  client-id: ${AIRTHINGS_CLIENT_ID}
  client-secret: ${AIRTHINGS_CLIENT_SECRET}
  token-url: https://accounts-api.airthings.com/v1/token
  api-url: https://consumer-api.airthings.com/v1
  account-id: ${AIRTHINGS_ACCOUNT_ID}
sinope:
  broker-url: ${SINOPE_BROKER_URL:tcp://localhost:1883}
  topics:
    - zigbee2mqtt/thermostat-wc-rdc
    - zigbee2mqtt/thermostat-sous-sol
    - zigbee2mqtt/thermostat-sejour
    - zigbee2mqtt/thermostat-salon
    - zigbee2mqtt/thermostat-salle-de-bain-etage
    - zigbee2mqtt/thermostat-chambre-sous-sol
    - zigbee2mqtt/thermostat-chambre-parentale
    - zigbee2mqtt/thermostat-chambre-ethan
    - zigbee2mqtt/thermostat-chambre-clemence
cors:
  allowed-origins:
    - http://localhost:4200
    - https://iot.y-rog.com